# Generated by Django 5.0.6 on 2024-07-05 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
